### ISSUE TITLE
Materials and Tools for hand

### ISSUE THREAD

**Issue by aviggiano836** [Women-in-Computing-at-RIT/robotic-hand#1]
[based on this page](https://onedrive.live.com/view.aspx?resid=D1EAAFC0BDFA320E!4601&ithint=file%2cxlsx&app=Excel&authkey=!AOkhrCQmNYBPLys)
Giant drinking straw 1/2 inch diameter) | 5
Dacron fiber line | 5
Micro servo motor | 5
Extra large rubber bands (size #170) | 5
Felt | 5
Hot glue gun | 1
Cardboard | 5
Scissors | 1
Clear tape | 1
Marker | 1
5 volt power supply | 1
Solderless breadboard jumper wires | 29
Electrical tape (red and black) | 1
Pin header strip | 1

**Comment by gen1e** [comment]
Needed felt and rubber bands which we now have
