### ISSUE TITLE
Meterials for the sensorized glove

### ISSUE THREAD

**Issue by dquach217** [Women-in-Computing-at-RIT/robotic-hand#2]
[Based on This](https://onedrive.live.com/view.aspx?resid=D1EAAFC0BDFA320E!4601&ithint=file%2cxlsx&app=Excel&authkey=!AOkhrCQmNYBPLys)

- Rubber bands (size #16) | 3
- Velostat sheet (pressure sensitive conductive plastic) | 1
- Copper tape | 1
- Wire solid core (WHS22-09-100)  | 1
- Mini breadboard (55 holes) | 1
- Piece of cardboard (or empty cereal box) | 1
- Metric ruler | 1
- Scissors | 1
- Clear tape | 1
- Hole punch | 1
- Wire strippers | 1
- Breadboard jumper wires | 13
- 100 Ohm Resistors | 5
- Breadboard (5cm x 3.5cm) | 1
- USB Cable for Arduino  | 1
- Arduino Uno  | 1

**Comment by gen1e** [comment]
We were missing rubber bands, but now have them
